import os, csv, json
from snakemake.utils import min_version

min_version("7.32.4")

configfile: "config/config.yml"


### helper functions

def pathCreator(dir):
    """ Return a lambda function that joins paths with the specified dir
        Useful for not repeating paths all the time in rules
    """
    return lambda *args: os.path.join(dir, *args)

### create log dirs

logdirs = ["default",
          "all",
          "correct_format",
          "extract_metadata",
          "reduce_metadata",
          "build_taxonomy",
          "import_q2",
          "train"]

## directory variables and functions

for d in logdirs:
    os.makedirs(os.path.join("logs", d), exist_ok = True)

proj_dir = os.path.join(config["outdir"], config["proj_name"])

metadata_dir = pathCreator(os.path.join(proj_dir, "metadata"))
qiime2_dir = pathCreator(os.path.join(proj_dir, "qiime2"))

## conda environment variables

code_dir = os.path.abspath(os.getcwd())
conda_env_dir = os.path.join(code_dir, "workflow", "envs")
conda_qiime2 = os.path.join(conda_env_dir, f"qiime2-amplicon-{config['q2_version']}-py38-linux-conda.yml")
conda_correct = os.path.join(conda_env_dir, "correct.yml")

## correct format file

correct_format_filepath = os.path.join(code_dir, "resources", config["correction_file"])

## output handling

alloutput = list()
alloutput.append(qiime2_dir("classifier", "fid_classifier.qza"))

rule all:
    input:
        alloutput

### load rules

include: "rules/correct_format.smk"
include: "rules/extract_metadata.smk"
include: "rules/reduce_metadata.smk"
include: "rules/build_taxonomy.smk"
include: "rules/import_q2.smk"
include: "rules/train.smk"