__default__:
    jobname: default
    time: 1-00:00:00 # time limit for each job
    ncpus: 1
    memory: 2G
    output: logs/default/job_default_%j.out
    error: logs/default/job_default_%j.err

all:
    jobname: all
    time: 0-00:05:00
    ncpus: 1
    memory: 50
    output: logs/all/all_%j.out
    error: logs/all/all_%j.err

fid_correct_format:
    jobname: fid_correct_format
    time: 0-00:10:00
    ncpus: 1
    memory: 500
    output: logs/fid_correct_format/fid_correct_format_%j.out
    error: logs/fid_correct_format/fid_correct_format_%j.err

fid_extract_metadata:
    jobname: fid_extract_metadata
    time: 0-00:10:00
    ncpus: 1
    memory: 500
    output: logs/fid_extract_metadata/fid_extract_metadata_%j.out
    error: logs/fid_extract_metadata/fid_extract_metadata_%j.err

fid_reduce_metadata:
    jobname: fid_reduce_metadata
    time: 0-00:10:00
    ncpus: 1
    memory: 500
    output: logs/fid_reduce_metadata/fid_reduce_metadata_%j.out
    error: logs/fid_reduce_metadata/fid_reduce_metadata_%j.err

fid_build_taxonomy:
    jobname: fid_build_taxonomy
    time: 0-00:10:00
    ncpus: 1
    memory: 500
    output: logs/fid_build_taxonomy/fid_build_taxonomy_%j.out
    error: logs/fid_build_taxonomy/fid_build_taxonomy_%j.err

fid_import_q2:
    jobname: fid_import_q2
    time: 0-01:00:00
    ncpus: 1
    memory: 500
    output: logs/fid_import_q2/fid_import_q2_%j.out
    error: logs/fid_import_q2/fid_import_q2_%j.err

train:
    jobname: train
    time: 0-02:00:00
    ncpus: 2
    memory: 90G
    output: logs/train/train_%j.out
    error: logs/train/train_%j.err