########################
# IMPORTANT INFORMATION:
#
# Variables commented with [ #cluster# ] must be
# changed accordingly in cluster_config.yml
########################


### General ###

proj_name: fusariumid-q2-2024.2     #-------#    Project name
outdir: /scratch/salias/projects    #-------#    Directory with all projects
q2_version: "2024.2"                #-------#    QIIME 2 version
py_version: "38"                    #-------#    Python version (as in the QIIME 2 YAML filename)

### Databases ###

db_dir: /home/salias/data/sf_databases/FUSARIUM-ID/raw_db    #-------#    Directory where database is stored
db_file: FUSARIUMID_v.3.0_TEF1.fas                           #-------#    Database filename
correction_file: corrections.tsv                             #-------#    Headerless 2-column TSV file containing original and replacement strings for correcting FUSARIUM-ID format inconsistencies

### Download TEF1 sequences from NCBI GenBank ###

query_file: query.txt    #-------#    File containing the query for the GenBank TEF1 sequence search (adapted from 10.1371/journal.pone.0207988)
download_njobs: 5        #-------#    Number of concurrent download connections

### Extract amplicon sequences with PCR primers ###

extract_primers: True    #-------#    True if you want to extract amplicon with primers, False otherwise (the rest of options in this section will be ignored then)
primer_f: EFseqF350      #-------#    Forward primer name present in resources/TEF1_primers.tsv or custom sequence
primer_r: EFseqR         #-------#    Reverse primer name present in resources/TEF1_primers.tsv or custom sequence
extract_n_threads: 2     #cluster#    Number of threads to use for multithreaded processing
