########################
# IMPORTANT INFORMATION:
#
# Variables commented with [ #cluster# ] must be
# changed accordingly in cluster_config.yml
########################


### General ###

proj_name: fusariumid-q2-2024.10    #-------#    Project name
outdir: /scratch/salias/projects    #-------#    Directory with all projects
q2_version: "2024.10"               #-------#    QIIME 2 version
py_version: "310"                   #-------#    Python version (as in the QIIME 2 YAML filename)

### Databases ###

db_dir: /home/salias/data/sf_databases/FUSARIUM-ID/raw_db    #-------#    Directory where database is stored
db_file: FUSARIUMID_v.3.0_TEF1.fas                           #-------#    Database filename
correction_file: corrections.tsv                             #-------#    Headerless 2-column TSV file containing original and replacement strings for correcting FUSARIUM-ID format inconsistencies

